# Generated by Django 5.1.1 on 2024-12-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True, help_text='URL de una imagen representativa', max_length=300, null=True)),
            ],
        ),
    ]
